# Generated by Django 4.1 on 2022-08-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='pro_pic.png', null=True, upload_to='questions/'),
        ),
    ]
