# Generated by Django 4.1 on 2022-08-28 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_questfollower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questfollower',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='pro_pic.png', null=True, upload_to='question/'),
        ),
    ]
