# Generated by Django 4.1 on 2022-08-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_questfollower_user_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='badgetype',
            name='desc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
